import Link from "next/link";
import { ChangeItem } from "@/components/change-item";
import { IntelligenceNav } from "@/components/intelligence-nav";
import { PeriodSelector } from "@/components/period-selector";
import { allChanges, filterChangesByPeriod, selectedPeriod, sincePreviousChanges } from "@/lib/data/intelligence-changes";
import { listCompanyIntelligenceSnapshots } from "@/lib/data/company-intelligence";

const readablePeriod = (period: string) => period === "previous" ? "since each company’s previous stored observation" : period === "all" ? "across all available history" : `within the latest ${period}-day evidence window`;
export default async function PortfolioBrief({ searchParams }: { searchParams: Promise<{ period?: string }> }) {
  const query = await searchParams; const period = selectedPeriod(query.period); const profiles = await listCompanyIntelligenceSnapshots();
  const complete = period === "previous" ? profiles.flatMap(sincePreviousChanges).sort((a,b)=>b.date.localeCompare(a.date)) : filterChangesByPeriod(allChanges(profiles), period);
  const companies = new Set(complete.map((item)=>item.company_id));
  const count = (type: string) => complete.filter((item)=>item.type===type).reduce((sum,item)=>sum+item.count,0);
  const failedSources = profiles.flatMap((profile)=>profile.source_freshness.filter((source)=>String(source.health).toLowerCase()!=="healthy").map((source)=>({profile,source})));
  const shallow = profiles.filter((profile)=>(profile.careers_history?.length ?? 0)<3);
  return <main className="portfolio-brief"><IntelligenceNav/><header><p className="eyebrow">PIOTW outside-in factual intelligence</p><h1>Portfolio brief</h1><p>A concise evidence-backed briefing for customer testing. Counts describe what PIOTW observed; they do not indicate importance, risk or operational health.</p><PeriodSelector period={period}/></header>
    <section className="portfolio-summary"><div><p className="eyebrow">Portfolio since last observation</p><h2>{companies.size} companies have recorded factual change</h2><p>{readablePeriod(period)}.</p></div><dl><div><dt>New careers observations</dt><dd>{count("CAREERS_APPEARED")}</dd></div><div><dt>Careers lifecycle changes</dt><dd>{count("CAREERS_ABSENT_ONCE")+count("CAREERS_CONFIRMED_CLOSED")+count("CAREERS_REOPENED")}</dd></div><div><dt>Atomic observations</dt><dd>{count("ATOMIC_OBSERVATION")}</dd></div><div><dt>Source-health changes</dt><dd>{count("SOURCE_HEALTH_CHANGE")}</dd></div><div><dt>Resolved procurement changes</dt><dd>{count("PROCUREMENT_RELEASE")+count("PROCUREMENT_REVISION")}</dd></div></dl></section>
    <section className="portfolio-latest"><header><p className="eyebrow">Latest company changes</p><h2>What PIOTW recorded most recently</h2><p>Shown because these are the newest factual records in the selected period.</p></header><div>{complete.slice(0,8).map((item)=><ChangeItem key={item.id} item={item}/>)}</div></section>
    <section className="companies-new-evidence"><header><p className="eyebrow">Companies with new evidence</p><h2>Evidence changed since the prior stored observation</h2><p>Shown because new factual evidence has been recorded—not because PIOTW has assessed importance.</p></header><div>{[...companies].map((id)=>{const profile=profiles.find((item)=>item.company_id===id);const total=complete.filter((item)=>item.company_id===id).length;return profile?<Link key={id} href={`/intelligence/${id}`}><strong>{profile.display_name}</strong><span>{total} factual change {total===1?"item":"items"}</span><small>Open company briefing →</small></Link>:null})}</div></section>
    <section className="portfolio-gaps"><header><p className="eyebrow">Data gaps</p><h2>Where PIOTW is currently blind or shallow</h2></header><div><article><h3>Failed or degraded sources</h3>{failedSources.length?<ul>{failedSources.map(({profile,source})=><li key={`${profile.company_id}-${String(source.source_family)}`}>{profile.display_name}: {String(source.source_family).replaceAll("_"," ")} — {String(source.health)}</li>)}</ul>:<p>None recorded.</p>}</article><article><h3>Shallow histories</h3><p>{shallow.length} of {profiles.length} company profiles have fewer than three careers snapshots. All current careers histories remain early.</p></article><article><h3>Unavailable source families</h3><p>Resolved company-level procurement evidence is unavailable. Issuer development observations are available only for Tesla. Benchmarks and predictions are NOT YET VALIDATED.</p></article></div></section>
    <footer><span>No score · no ranking · no prediction</span><Link href="/intelligence">Continue to watchlist →</Link></footer></main>;
}
