import { useState } from "react";
import pilotV02 from "../data/derived/pilot_v02_demo.json";

type Company = {id:string;name:string;ticker:string;sector:string;pressure:number;confidence:number;outcome:number;summary:string};
const companies: Company[] = [
  {id:"chemring",name:"Chemring Group",ticker:"CHG",sector:"Aerospace & defence",pressure:15,confidence:63,outcome:1,summary:"Strong cash conversion and improving margins outweighed disclosed labour and supply-chain pressure."},
  {id:"vesuvius",name:"Vesuvius",ticker:"VSVS",sector:"Industrial materials",pressure:75,confidence:62,outcome:1,summary:"Freight disruption, working-capital absorption, deliberate inventory build and a quantified capacity programme aligned."},
  {id:"bodycote",name:"Bodycote",ticker:"BOY",sector:"Industrial services",pressure:26,confidence:61,outcome:0,summary:"Automotive disruption and a guidance reduction were offset by healthy margins, cash flow and pricing recovery."},
];
const evidence: Record<string,{label:string;value:number;type:"support"|"contradict";source:string}[]> = {
  chemring:[{label:"Labour and supply-chain pressures expected into 2022",value:13,type:"support",source:"FY21 results · p4"},{label:"Order book covered 84% of expected 2022 revenue",value:12,type:"support",source:"FY21 results · p5"},{label:"Cash conversion 105%; net debt down 45%",value:-18,type:"contradict",source:"FY21 results · p1"},{label:"Operating margin improved to 14.6%",value:-14,type:"contradict",source:"FY21 results · p10"}],
  vesuvius:[{label:"Supply disruption caused £10.3m excess freight cost",value:19,type:"support",source:"H1 2021 results · p1"},{label:"£28m capacity expansion announced",value:18,type:"support",source:"H1 2021 results · p6"},{label:"Cash conversion fell to 52% as working capital rose",value:17,type:"support",source:"H1 2021 results · p12"},{label:"Working capital/sales improved to 20.7%",value:-12,type:"contradict",source:"H1 2021 results · p6"}],
  bodycote:[{label:"Automotive revenue fell due to supply bottlenecks",value:15,type:"support",source:"Nov 2021 update · p1"},{label:"Full-year revenue expectation cut by up to £10m",value:14,type:"support",source:"Nov 2021 update · p1"},{label:"Cash flow strong and margins healthy",value:-16,type:"contradict",source:"Nov 2021 update · p2"},{label:"Inflation being passed through to customers",value:-10,type:"contradict",source:"Nov 2021 update · p2"}],
};
const results=[{name:"Inventory/revenue baseline",brier:0.268},{name:"PIOTW operational",brier:0.286},{name:"Financial stress count",brier:0.347},{name:"Margin deterioration",brier:0.440},{name:"Leave-one-out base rate",brier:0.500}];
type V02Prediction = {company_id:string;model:string;horizon_months:number;probability:number;confidence:number;coverage:number;missing_families:string[]};
const v02Predictions = pilotV02.predictions as V02Prediction[];
const v02CompanyNames:Record<string,string>={chemring:"Chemring",vesuvius:"Vesuvius",bodycote:"Bodycote"};
const nav=["Universe","Company profile","Evidence ledger","System map","Signal model","Backtest lab"];
const sourceRows=[
  ["Jobs","Greenhouse · Lever · Ashby · SmartRecruiters · Recruitee","Public feeds built","Weekly"],
  ["Company records","Companies House","Free key required","Daily/weekly"],
  ["Contracts","Contracts Finder OCDS","Public read API built","Daily"],
  ["Sector context","ONS","Open API built","On release"],
  ["Company disclosures","RNS / investor-relations documents","Document pipeline working","Daily"],
  ["US filings","SEC EDGAR","No-key API built","Daily"],
];
const signalFamilies=[
  ["Workforce demand & skills",15,22,"Hiring velocity, function mix, seniority, new sites"],
  ["Operational disclosure",16,10,"Delivery, quality, shortages, utilisation, working capital"],
  ["Leadership & organisation",12,12,"Executive churn, interim roles, transformation leadership"],
  ["Capacity & footprint",10,16,"Facilities, capex, closures, commissioning"],
  ["Procurement & contracts",9,12,"Awards, order intake, concentration, delays"],
  ["Product & quality",12,8,"Recalls, regulators, warranty, certification"],
  ["Corporate actions",7,6,"Filings, officers, acquisitions, charges"],
  ["Web & narrative",7,6,"Page changes, cadence, changed targets"],
  ["Sector & macro",7,4,"Output, vacancies, prices, supply conditions"],
  ["Financial state",5,4,"Margin, cash, inventory, leverage, guidance"],
];

export default function Home(){
 const [view,setView]=useState("Universe"); const [selected,setSelected]=useState(companies[1]);
 const open=(c:Company)=>{setSelected(c);setView("Company profile")}; const rows=evidence[selected.id];
 const v02ForSelected=v02Predictions.filter(p=>p.company_id===v02CompanyNames[selected.id]&&p.horizon_months===18);
 return <main><aside><div className="brand"><div className="brand-mark"><span/><span/><span/></div><div><b>PUT IT ON<br/>THE WALL</b><small>INTELLIGENCE</small></div></div><nav>{nav.map(n=><button key={n} className={view===n?"active":""} onClick={()=>setView(n)}><span>{n[0]}</span>{n}</button>)}</nav><div className="gate"><div className="eyebrow">STAGE-GATE DECISION</div><b>Gate 4 · Not passed</b><div className="gate-line"><i style={{width:"67%"}}/></div><small>Operational model did not beat the best simple baseline.</small></div></aside><section className="shell"><header><div><span className="status-dot"/> RETROSPECTIVE PILOT <em>CUTOFF 31 DEC 2021</em></div><button className="version">RESEARCH MVP 0.2</button></header>
 {view==="Universe"&&<div className="content"><div className="title-row"><div><p className="kicker">REAL PUBLIC EVIDENCE · EXPLORATORY</p><h1>Three-company pilot</h1><p>Hash-selected before outcome inspection. One retained pre-cutoff disclosure per company.</p></div><div className="snapshot"><strong>24</strong><span>checked observations</span><small>£0 external spend</small></div></div><div className="notice"><b>Research integrity note</b><span>This is a protocol-frozen retrospective feasibility test, not a blind or statistically powered backtest.</span></div><div className="table-card"><div className="table-head"><span>COMPANY</span><span>MODEL PROB.</span><span>CONFIDENCE</span><span>ACTUAL LABEL</span><span>SELECTION</span><span>STATUS</span></div>{companies.map(c=><button className="company-row" key={c.id} onClick={()=>open(c)}><span className="company"><b>{c.name}</b><small>{c.ticker} · {c.sector}</small></span><span><b className={c.pressure>50?"hot":""}>{c.pressure}%</b><i className="micro"><i style={{width:`${c.pressure}%`}}/></i></span><span><b>{c.confidence}%</b></span><span><b>{c.outcome?"Observed":"Not observed"}</b></span><span><b>Fixed hash</b></span><span><b>{(c.pressure>=50?1:0)===c.outcome?"Correct":"Miss"}</b></span></button>)}</div><div className="bottom-grid"><div className="panel"><p className="kicker">DECISION</p><h3>Do not expand this model as proprietary intelligence yet.</h3><p>It ranked Vesuvius correctly but missed Chemring’s later capacity programme and scored worse than the inventory/revenue baseline. The pilot supports data feasibility, not incremental alpha.</p></div><div className="panel metrics"><div><strong>1/2</strong><span>positive outcomes found</span></div><div><strong>0.286</strong><span>PIOTW Brier score</span></div><div><strong>£0</strong><span>external spend</span></div></div></div></div>}
 {view==="Company profile"&&<div className="content"><button className="back" onClick={()=>setView("Universe")}>← Pilot universe</button><div className="company-title"><div><p className="kicker">{selected.ticker} · {selected.sector.toUpperCase()}</p><h1>{selected.name}</h1><p>{selected.summary}</p></div><div className="confidence"><span>V0.1 EVIDENCE CONFIDENCE</span><strong>{selected.confidence}%</strong><small>Eight manually checked facts</small></div></div><div className="score-grid"><div className="score-card"><div className="score-top"><span>V0.1 composite probability</span><strong>{selected.pressure}%</strong></div><div className="meter"><i style={{width:`${selected.pressure}%`}}/></div></div>{v02ForSelected.map(p=><div className="score-card" key={p.model}><div className="score-top"><span>V0.2 {p.model==="operational_pressure"?"pressure":"expansion"} demo</span><strong>{Math.round(p.probability*100)}%</strong></div><div className="meter"><i className={p.model==="operational_pressure"?"":"blue"} style={{width:`${p.probability*100}%`}}/></div><small>{Math.round(p.coverage*100)}% weighted coverage</small></div>)}<div className="score-card"><div className="score-top"><span>Actual qualifying event</span><strong>{selected.outcome?"Yes":"No"}</strong></div></div><div className="score-card"><div className="score-top"><span>V0.1 result</span><strong>{(selected.pressure>=50?1:0)===selected.outcome?"Correct":"Miss"}</strong></div></div></div><div className="notice model-warning"><b>Do not compare v0.1 and v0.2 as competing results</b><span>V0.2 is an integration demonstration using the same sparse evidence. Its low coverage is intentional and prevents false confidence.</span></div><div className="panel why"><div className="panel-title"><div><p className="kicker">AUDIT TRAIL</p><h2>Why the v0.1 probability is {selected.pressure}%</h2></div><button onClick={()=>setView("Evidence ledger")}>Ledger</button></div><p className="caution">Every item was public by the cutoff. Later outcome documents are stored separately.</p>{rows.map((x,i)=><div className="contribution" key={i}><span className={x.value>0?"plus":"minus"}>{x.value>0?"+":""}{x.value}</span><div><b>{x.label}</b><small>{x.source}</small></div><i className={x.type} style={{width:`${Math.abs(x.value)*3.7}px`}}/></div>)}</div></div>}
 {view==="Evidence ledger"&&<div className="content"><button className="back" onClick={()=>setView("Company profile")}>← {selected.name}</button><p className="kicker">FACT → SIGNAL → INFERENCE</p><h1>Evidence ledger</h1><p className="lede">Only directly supported observations enter the ledger. Alternative explanations remain explicit.</p><div className="ledger-grid"><div className="ledger support"><h3>Supporting evidence</h3>{rows.filter(x=>x.type==="support").map((x,i)=><article key={i}><b>{x.label}</b><small>{x.source}</small></article>)}</div><div className="ledger contradict"><h3>Contradicting evidence</h3>{rows.filter(x=>x.type==="contradict").map((x,i)=><article key={i}><b>{x.label}</b><small>{x.source}</small></article>)}</div><div className="ledger alternative"><h3>Alternative explanations</h3><article><b>Sector-wide pandemic supply disruption</b><small>Weakens company-specific attribution</small></article><article><b>Deliberate growth investment</b><small>Capacity signals need not imply operational failure</small></article></div><div className="ledger unknown"><h3>Unknown / missing</h3><article><b>Internal delivery and quality measures</b><small>Not publicly disclosed</small></article><article><b>Independent customer or supplier evidence</b><small>Single-source dependence limits confidence</small></article></div></div></div>}
 {view==="System map"&&<div className="content"><p className="kicker">HOW THE PRODUCT WORKS</p><h1>From public evidence to a testable prediction</h1><p className="lede">The score is the end of a documented chain—not an answer generated by AI.</p><div className="flow"><article><span>01</span><b>Collect</b><small>Public jobs, filings, contracts, releases and sector data</small></article><i>→</i><article><span>02</span><b>Preserve</b><small>URL, public date, retrieval date, raw hash and source identity</small></article><i>→</i><article><span>03</span><b>Measure</b><small>Change, persistence, novelty, materiality and peer difference</small></article><i>→</i><article><span>04</span><b>Score</b><small>Pressure and expansion separately at 6, 12 and 18 months</small></article><i>→</i><article><span>05</span><b>Test</b><small>Reveal later outcomes and compare with simple baselines</small></article></div><div className="bottom-grid"><div className="panel"><p className="kicker">THE ALGORITHM</p><h3>Transparent weighted evidence</h3><p>Family weight × strength × source reliability × measurement quality × materiality × time decay × independence × relevance × direction. Event clusters are capped so ten copies of one announcement cannot become ten facts.</p></div><div className="panel"><p className="kicker">WHAT AI DOES NOT DO</p><h3>AI does not choose the score</h3><p>Text assistance may later propose candidate facts for review. Eligibility, calculations, cutoffs, weights, confidence and evaluation remain deterministic and reconstructable.</p></div></div><div className="table-card source-table"><div className="table-head"><span>DATA FAMILY</span><span>SOURCE</span><span>ACCESS</span><span>CADENCE</span></div>{sourceRows.map(r=><div className="company-row" key={r[0]}>{r.map(v=><span key={v}><b>{v}</b></span>)}</div>)}</div></div>}
 {view==="Signal model"&&<div className="content"><p className="kicker">MODEL 0.2 · PROPOSED PRIORS</p><h1>Two questions, different weights</h1><p className="lede">Pressure asks what may go wrong or require intervention. Expansion asks what may grow or transform. A signal can point differently in each model.</p><div className="table-card signal-table"><div className="table-head"><span>FAMILY</span><span>PRESSURE</span><span>EXPANSION</span><span>WHAT IS MEASURED</span></div>{signalFamilies.map(r=><div className="company-row" key={String(r[0])}><span><b>{r[0]}</b></span><span><b>{r[1]}%</b><i className="micro"><i style={{width:`${Number(r[1])*4}%`}}/></i></span><span><b>{r[2]}%</b><i className="micro blue"><i style={{width:`${Number(r[2])*4}%`}}/></i></span><span><small>{r[3]}</small></span></div>)}</div><div className="notice model-warning"><b>Weights are hypotheses</b><span>They are frozen before a larger test, then retained only if they improve out-of-time accuracy, calibration or lead time. No weight is accepted because it makes the original three companies look good.</span></div></div>}
 {view==="Backtest lab"&&<div className="content"><p className="kicker">MODEL COMPARISON</p><h1>Backtest laboratory</h1><div className="notice"><b>Gate 4 failed</b><span>Lower Brier is better. The operational model did not outperform the best simple baseline.</span></div><div className="table-card"><div className="table-head" style={{gridTemplateColumns:"2fr 1fr 2fr"}}><span>MODEL</span><span>BRIER</span><span>INTERPRETATION</span></div>{results.map((r,i)=><div className="company-row" style={{gridTemplateColumns:"2fr 1fr 2fr"}} key={r.name}><span><b>{r.name}</b></span><span><b>{r.brier.toFixed(3)}</b></span><span><b>{i===0?"Best in this tiny pilot":r.name.startsWith("PIOTW")?"Second; no incremental alpha":"Comparator"}</b></span></div>)}</div><div className="panel" style={{marginTop:20}}><h3>What this result permits</h3><p>It permits a claim that the evidence architecture and leakage controls are feasible. It does not permit a claim of predictive superiority, statistical significance, generalisability or proprietary intelligence.</p></div></div>}
 </section></main>;
}
