import Link from "next/link";
import { CareersHistory } from "@/components/careers-history";
import { ChangeItem } from "@/components/change-item";
import { IntelligenceNav } from "@/components/intelligence-nav";
import { PeriodSelector } from "@/components/period-selector";
import { filterChangesByPeriod, profileChanges, sincePreviousChanges, type IntelligencePeriod } from "@/lib/data/intelligence-changes";
import type { AtomicObservationV037, CompanyIntelligenceSnapshot, FactualObservation, Provenance } from "@/types/company-intelligence";

const readable = (value: unknown) => value === null || value === undefined ? "Not available" : typeof value === "boolean" ? value ? "Yes" : "No" : String(value).replaceAll("_", " ");
const dateTime = (value: string) => new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/London" }).format(new Date(value));
const dateOnly = (value: string) => new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value));
const provenanceLinks = (observation: FactualObservation) => observation.provenance.filter((item): item is Provenance & { source_url: string } => Boolean(item.source_url));

type TimelineItem = { id: string; date: string; source: string; statement: string; status: string; url?: string | null };
function timeline(profile: CompanyIntelligenceSnapshot): TimelineItem[] {
  const atomic = (profile.atomic_observations ?? []).filter((item) => item.decision === "ACCEPT").map((item) => ({ id: item.observation_id, date: item.publication_date, source: "Issuer document", statement: `${item.subject} ${item.action_or_state} ${item.object}.`, status: item.timing, url: item.source_url }));
  const careers = (profile.careers_history ?? []).flatMap((point, index) => {
    const items: TimelineItem[] = [{ id: `snapshot-${point.observed_at}`, date: point.observed_at, source: "Careers / ATS", statement: `A careers snapshot observed ${point.open_roles} open roles.`, status: index < 2 ? "EARLY HISTORY" : "OBSERVED" }];
    if (point.new_roles) items.push({ id: `new-${point.observed_at}`, date: point.observed_at, source: "Careers / ATS", statement: point.new_roles === 1 ? "1 role was newly observed in this snapshot." : `${point.new_roles} roles were newly observed in this snapshot.`, status: "NEWLY OBSERVED" });
    if (point.absent_once_roles) items.push({ id: `absent-${point.observed_at}`, date: point.observed_at, source: "Careers / ATS", statement: point.absent_once_roles === 1 ? "1 role was absent once and remains open pending a second healthy absence." : `${point.absent_once_roles} roles were absent once and remain open pending a second healthy absence.`, status: "UNCONFIRMED ABSENCE" });
    if (point.confirmed_closed_roles) items.push({ id: `closed-${point.observed_at}`, date: point.observed_at, source: "Careers / ATS", statement: `${point.confirmed_closed_roles} roles met the confirmed-closure rule.`, status: "CONFIRMED CLOSED" });
    if (point.reopened_roles) items.push({ id: `reopened-${point.observed_at}`, date: point.observed_at, source: "Careers / ATS", statement: point.reopened_roles === 1 ? "1 role reopened." : `${point.reopened_roles} roles reopened.`, status: "REOPENED" });
    return items;
  });
  return [...atomic, ...careers].sort((a, b) => b.date.localeCompare(a.date));
}

function AtomicCard({ item }: { item: AtomicObservationV037 }) {
  return <article><span className="atomic-development">DEVELOPMENT EXTRACTION — NOT YET VALIDATED</span><h3>{item.subject} {item.action_or_state} {item.object}.</h3>
    <div className="evidence-path"><span>Observation</span><i>→</i><span>Evidence</span><i>→</i><span>Source</span></div>
    <blockquote>{item.evidence_span}</blockquote>{item.source_url ? <a href={item.source_url} target="_blank" rel="noreferrer">Open source document ↗</a> : <span>Source URL unavailable</span>}
    <dl><div><dt>Source date</dt><dd>{dateOnly(item.publication_date)}</dd></div><div><dt>Timing</dt><dd>{readable(item.timing)}</dd></div><div><dt>Entity</dt><dd>{readable(item.entity_relationship)}</dd></div><div><dt>Scope</dt><dd>{readable(item.scope)}</dd></div></dl>
    <details><summary>Technical provenance</summary><dl><div><dt>Observation ID</dt><dd>{item.observation_id}</dd></div><div><dt>Source ID</dt><dd>{item.source_id}</dd></div><div><dt>Source hash</dt><dd><code>{item.source_hash}</code></dd></div><div><dt>Extractor</dt><dd>{item.extractor_version}</dd></div><div><dt>Model</dt><dd>{item.model_version}</dd></div></dl></details>
  </article>;
}

export function CompanyMonitoringProfile({ profile, period = "previous" }: { profile: CompanyIntelligenceSnapshot; period?: IntelligencePeriod }) {
  const observed = profile.dimensions.flatMap((dimension) => dimension.observations.map((observation) => ({ dimension, observation })));
  const atomicFacts = (profile.atomic_observations ?? []).filter((item) => item.decision === "ACCEPT");
  const sparse = profile.dimensions.filter((item) => item.coverage_status !== "OBSERVED");
  const history = profile.careers_history ?? []; const current = history.at(-1); const items = timeline(profile);
  const completeChanges = profileChanges(profile); const changes = period === "previous" ? sincePreviousChanges(profile) : filterChangesByPeriod(completeChanges, period); const previous = history.at(-2);
  const issuerSincePrevious = atomicFacts.filter((item) => !previous || item.publication_date > previous.observed_at).length;
  return <article className="truth-profile"><IntelligenceNav companyId={profile.company_id}/>
    <header className="truth-header"><div><p className="eyebrow">Portfolio intelligence · evidence view</p><h1>{profile.display_name}</h1><p>Snapshot generated {dateTime(profile.observation_date)}</p></div><div className="truth-status"><strong>NO SCORE</strong><span>Observed facts only</span></div><dl><div><dt>Latest evidence</dt><dd>{items[0] ? dateOnly(items[0].date) : "Not available"}</dd></div><div><dt>Careers snapshots</dt><dd>{history.length}</dd></div><div><dt>Atomic facts</dt><dd>{atomicFacts.length}</dd></div><div><dt>Prediction</dt><dd>NOT YET VALIDATED</dd></div></dl></header>

    <section className="company-briefing"><header><p className="eyebrow">60-second factual briefing</p><h2>{period === "previous" ? "Since the previous observation" : period === "all" ? "Across all available history" : `Within the latest ${period}-day evidence window`}</h2><p>Deterministic differences only. No significance or direction is inferred.</p><PeriodSelector period={period}/></header><div className="briefing-grid"><article><h3>Careers movement</h3>{current ? <ul><li><strong>{current.new_roles}</strong> newly observed roles</li><li><strong>{current.persistent_roles}</strong> roles persisted</li><li><strong>{current.absent_once_roles}</strong> became absent once</li><li><strong>{current.confirmed_closed_roles}</strong> confirmed closures</li><li><strong>{current.reopened_roles}</strong> reopened roles</li><li><strong>{issuerSincePrevious}</strong> issuer observations since the prior careers observation</li></ul> : <p>INSUFFICIENT OBSERVED DATA for careers differences.</p>}</article><article><h3>Latest evidence</h3><p className="brief-explanation">Appears because {changes.length} factual records fall within the selected period.</p>{changes.slice(0,5).map((item)=><ChangeItem key={item.id} item={item} compact />)}{!changes.length ? <p>INSUFFICIENT OBSERVED DATA</p> : null}</article><article><h3>Sources PIOTW sees / gaps</h3><ul><li>{history.length} careers snapshots available</li><li>{profile.source_freshness.filter((source)=>String(source.health).toLowerCase()==="healthy").length} currently healthy {profile.source_freshness.filter((source)=>String(source.health).toLowerCase()==="healthy").length === 1 ? "source" : "sources"}</li><li>{atomicFacts.length ? "Issuer development observations available" : "Issuer observations unavailable"}</li><li>Procurement unavailable until supplier resolution is approved</li><li>{sparse.length} operational dimensions remain unobserved</li></ul><Link className="brief-print-link" href={`/intelligence/${profile.company_id}/brief?period=${period}`}>Open print/share evidence brief →</Link></article></div></section>

    <section className="truth-change"><div><p className="eyebrow">What changed?</p><h2>A chronological record of observable company activity.</h2><p>No significance, direction or risk is inferred.</p></div>{items.length ? <ol className="change-timeline">{items.map((item) => <li key={item.id}><time>{dateOnly(item.date)}</time><div><span>{item.source} · {item.status}</span><p>{item.statement}</p>{item.url ? <a href={item.url} target="_blank" rel="noreferrer">View provenance ↗</a> : <small>Source record retained internally</small>}</div></li>)}</ol> : <p>INSUFFICIENT OBSERVED DATA</p>}</section>

    <section className="known-unknown"><article><p className="eyebrow">What PIOTW currently knows</p><h2>Evidence in hand</h2><ul><li><strong>{history.length}</strong> careers snapshots</li><li><strong>{current?.open_roles ?? "—"}</strong> currently observed open roles</li><li><strong>{current?.absent_once_roles ?? "—"}</strong> roles absent once, not treated as closed</li><li><strong>{atomicFacts.length}</strong> development atomic observations</li></ul></article><article><p className="eyebrow">What PIOTW does not yet know</p><h2>Explicit gaps</h2><ul><li>Procurement history is insufficient and unresolved suppliers are not attached.</li><li>{sparse.length} of 8 dimensions have INSUFFICIENT OBSERVED DATA.</li><li>Observation extraction is NOT YET VALIDATED.</li><li>Benchmarks, scores and predictions are NOT YET VALIDATED.</li></ul></article></section>

    <CareersHistory history={history} />

    <section className="atomic-facts"><header><p className="eyebrow">Traceable observations</p><h2>From plain fact to source evidence.</h2><p>Issuer-document observations shown here are development extractions. Careers observations are deterministic collection facts. Neither is a prediction.</p></header>{atomicFacts.length ? <div className="atomic-fact-grid">{atomicFacts.map((item) => <AtomicCard key={item.observation_id} item={item} />)}</div> : <p className="truth-empty">No issuer-document atomic observations are attached to this company.</p>}
      {observed.length ? <div className="deterministic-observations"><h3>Deterministic careers observations</h3>{observed.map(({ dimension, observation }) => <article key={observation.observation_id}><strong>{readable(observation.observation_type)}</strong><p>{readable(observation.state)} {observation.unit}; observed change {observation.change === null ? "not available" : `${observation.change > 0 ? "+" : ""}${observation.change}`}.</p><div className="truth-provenance">{provenanceLinks(observation).map((source, index) => <a key={`${source.source_hash}-${index}`} href={source.source_url} target="_blank" rel="noreferrer">Evidence {index + 1} ↗</a>)}</div><small>{dimension.name} · existing read-model relationship</small></article>)}</div> : null}</section>

    <section className="source-coverage"><header><p className="eyebrow">Source coverage & health</p><h2>What PIOTW can currently see</h2></header><div>{profile.source_freshness.map((source) => <article key={String(source.source_family)}><span>{readable(source.source_family)}</span><strong>{readable(source.health)}</strong><dl><div><dt>Available to this company</dt><dd>{source.last_successful_fetch ? "Yes" : "No"}</dd></div><div><dt>Last success</dt><dd>{source.last_successful_fetch ? dateTime(String(source.last_successful_fetch)) : "Not available"}</dd></div><div><dt>History depth</dt><dd>{String(source.source_family) === "careers_ats" ? `${history.length} snapshots` : "Insufficient"}</dd></div></dl></article>)}<article><span>Issuer observation layer</span><strong>{atomicFacts.length ? "DEVELOPMENT DATA AVAILABLE" : "NOT AVAILABLE"}</strong><dl><div><dt>Facts</dt><dd>{atomicFacts.length}</dd></div><div><dt>Validation</dt><dd>NOT YET VALIDATED</dd></div></dl></article></div></section>

    <section className="truth-dimensions"><div className="truth-section-title"><p className="eyebrow">Eight operational dimensions</p><h2>Visibility only—no dimension scores.</h2></div><div className="truth-grid">{profile.dimensions.map((dimension, index) => <article key={dimension.dimension_id} data-covered={dimension.coverage_status === "OBSERVED"}><header><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{dimension.name}</h3><p>{dimension.coverage_status === "OBSERVED" ? "OBSERVED FACTS AVAILABLE" : "INSUFFICIENT OBSERVED DATA"}</p></div></header>{dimension.observations.length ? <p>{dimension.observations.length} existing deterministic observation{dimension.observations.length === 1 ? "" : "s"}.</p> : <p className="truth-empty">No legitimately mapped observation in the current read model.</p>}<footer><span>Dimension score</span><strong>NOT YET VALIDATED</strong></footer></article>)}</div></section>

    <details className="truth-debug"><summary>Internal product debug</summary><div><h2>Snapshot trace</h2><dl><div><dt>Schema</dt><dd>{profile.schema_version}</dd></div><div><dt>Company ID</dt><dd>{profile.company_id}</dd></div><div><dt>Missing sources</dt><dd>{readable(profile.data_coverage.source_families_missing)}</dd></div><div><dt>Observation IDs</dt><dd>{[...atomicFacts.map((item) => item.observation_id), ...observed.map(({ observation }) => observation.observation_id)].join(", ") || "None"}</dd></div></dl></div></details>
    <nav className="truth-back"><Link href="/intelligence">← Return to watchlist</Link><Link href={`/intelligence/compare?companies=${profile.company_id}`}>Compare this company →</Link><Link href={`/intelligence/changes?company=${profile.company_id}`}>All factual changes →</Link></nav>
  </article>;
}
