import type { CompanyIntelligenceV01, IntelligenceEvidence, StageStatus } from "@/types/company-intelligence-v01";

const money = (value:number|null, currency:string|null) => value === null ? "WITHHELD" : new Intl.NumberFormat("en-GB",{style:"currency",currency:currency??"GBP",maximumFractionDigits:0}).format(value)+"m";
const statusLabel = (status:StageStatus) => status.replaceAll("_"," ");
function EvidenceLinks({ids,evidence}:{ids:string[];evidence:IntelligenceEvidence[]}) { const rows=ids.map(id=>evidence.find(item=>item.evidence_id===id)).filter((item):item is IntelligenceEvidence=>Boolean(item)); return <div className="contract-evidence">{rows.map(item=><a key={item.evidence_id} href={`#${item.evidence_id}`}>{item.evidence_id}</a>)}</div> }

export function CompanyValueIntelligence({ intelligence }: { intelligence:CompanyIntelligenceV01 }) {
  const availableComparison=intelligence.comparisons.find(item=>item.status==="AVAILABLE");
  const availableIntervention=intelligence.interventions.find(item=>item.status==="AVAILABLE");
  const availableImpact=intelligence.financial_impacts.find(item=>item.status==="AVAILABLE");
  return <main className="contract-intelligence">
    <header className="contract-hero"><div><p className="eyebrow">PIOTW COMPANY INTELLIGENCE v0.1</p><h1>{intelligence.company.display_name}</h1><p>{intelligence.conditions[0]?.statement ?? "No operational condition is supportable from available evidence."}</p></div><aside><span>OVERALL EVIDENCE CONFIDENCE</span><strong>{intelligence.overall_confidence}</strong><small>As of {new Date(intelligence.as_of).toLocaleDateString("en-GB")}</small></aside></header>
    <section className="contract-stagebar">{Object.entries(intelligence.capabilities).map(([stage,status])=><article key={stage} data-status={status}><span>{stage}</span><strong>{statusLabel(status)}</strong></article>)}</section>
    <section className="contract-lead"><article><p className="eyebrow">Measured anomaly</p><strong>{availableComparison?.gap === null || availableComparison?.gap === undefined ? "WITHHELD" : `${availableComparison.gap > 0 ? "+" : ""}${availableComparison.gap}${availableComparison.unit === "percentage points" ? "ppt" : ` ${availableComparison.unit}`}`}</strong><p>{availableComparison ? `${availableComparison.metric} versus ${availableComparison.peer_set_or_history}.` : "No comparison passed the evidence gate."}</p></article><article><p className="eyebrow">Driver-specific intervention</p><h2>{availableIntervention?.title ?? "WITHHELD"}</h2><p>{availableIntervention?.mechanism ?? availableIntervention?.withheld_reason}</p></article><article><p className="eyebrow">Financial consequence</p><div className="contract-range"><b>{money(availableImpact?.low??null,availableImpact?.currency??null)}</b><b>{money(availableImpact?.base??null,availableImpact?.currency??null)}</b><b>{money(availableImpact?.high??null,availableImpact?.currency??null)}</b></div><p>{availableImpact?.measure ?? availableImpact?.withheld_reason}</p></article></section>
    <section className="contract-grid"><header><p className="eyebrow">Detect</p><h2>Operational conditions</h2></header>{intelligence.conditions.map(item=><article key={item.condition_id}><span>{item.dimension} · {item.materiality}</span><h3>{item.title}</h3><p>{item.statement}</p><dl><div><dt>Direction</dt><dd>{item.direction}</dd></div><div><dt>Change</dt><dd>{item.change??"Not available"}</dd></div><div><dt>Evidence confidence</dt><dd>{item.evidence_confidence}</dd></div></dl><EvidenceLinks ids={item.evidence_ids} evidence={intelligence.evidence}/></article>)}{(intelligence.condition_qualifications??[]).filter(item=>item.status!=="QUALIFIED").map(item=><article key={item.qualification_id}><span>{item.dimension} · candidate assessment</span><h3>{item.candidate_type.replaceAll("_"," ")}</h3><strong>{item.status.replaceAll("_"," ")}</strong><h4>What we observed</h4><p>{item.what_observed}</p><h4>Why it might matter</h4><p>{item.why_it_might_matter}</p><h4>Why the evidence is weak</h4><p>{item.evidence_strength}</p><h4>What we still do not know</h4><ul>{item.missing_information.map((missing,index)=><li key={`${item.qualification_id}-missing-${index}`}>{missing}</li>)}</ul><h4>What would change PIOTW&apos;s view</h4><p>{item.what_would_change_view}</p><EvidenceLinks ids={item.evidence_ids} evidence={intelligence.evidence}/></article>)}</section>
    <section className="contract-sections"><article><p className="eyebrow">Compare</p><h2>Peer and historical context</h2>{intelligence.comparisons.map(item=><div key={item.comparison_id} className="contract-result"><strong>{item.metric}</strong>{item.status==="AVAILABLE"?<p>{item.target_value}{item.unit==="percentage points"?"%":""} versus {item.comparator_value}{item.unit==="percentage points"?"%":""}; gap {item.gap}ppt; n={item.sample_size}.</p>:<p><b>{statusLabel(item.status)}:</b> {item.withheld_reason}</p>}<EvidenceLinks ids={item.evidence_ids} evidence={intelligence.evidence}/></div>)}</article><article><p className="eyebrow">Predict</p><h2>What tends to happen next</h2>{intelligence.predictions.map(item=><div key={item.prediction_id} className="contract-result"><strong>{statusLabel(item.status)}</strong><p>{item.status==="AVAILABLE"?`${item.target_event} · ${(item.probability??0)*100}% · ${item.horizon}`:item.withheld_reason}</p></div>)}</article><article><p className="eyebrow">Prescribe</p><h2>Intervention hypothesis</h2>{intelligence.interventions.map(item=><div key={item.intervention_id} className="contract-result"><strong>{item.title??statusLabel(item.status)}</strong><p>{item.mechanism??item.withheld_reason}</p>{item.status==="AVAILABLE"?<details><summary>Investigation and falsifiers</summary><h4>Investigate</h4><ul>{item.investigation_steps.map(step=><li key={step}>{step}</li>)}</ul><h4>Falsified if</h4><ul>{item.falsifiers.map(step=><li key={step}>{step}</li>)}</ul></details>:null}<EvidenceLinks ids={item.evidence_ids} evidence={intelligence.evidence}/></div>)}</article><article><p className="eyebrow">Quantify</p><h2>Financial mechanism</h2>{intelligence.financial_impacts.map(item=><div key={item.impact_id} className="contract-result"><strong>{item.measure??statusLabel(item.status)}</strong>{item.status==="AVAILABLE"?<><p>{money(item.low,item.currency)} / {money(item.base,item.currency)} / {money(item.high,item.currency)} · {item.incremental?"incremental":"not incremental"}</p><ul>{item.assumptions.map(a=><li key={a.assumption_id}>{a.statement}: {a.value} {a.unit} — {a.basis}</li>)}</ul></>:<p>{item.withheld_reason}</p>}<EvidenceLinks ids={item.evidence_ids} evidence={intelligence.evidence}/></div>)}</article></section>
    <section className="contract-coverage"><article><p className="eyebrow">Coverage and uncertainty</p><h2>{intelligence.coverage.status} coverage</h2><p>{intelligence.coverage.evidence_count} evidence records · provenance {intelligence.coverage.provenance_complete?"complete":"incomplete"}.</p><h3>Still missing</h3><ul>{intelligence.coverage.source_families_missing.map(item=><li key={item}>{item.replaceAll("_"," ")}</li>)}</ul></article><article><p className="eyebrow">Remaining product blockers</p><h2>Explicitly not filled</h2><ul>{intelligence.missing_capabilities.map(item=><li key={item}>{item}</li>)}</ul><p><b>Scientific gate run:</b> {String(intelligence.scientific_gate_run)}</p></article></section>
    <section className="contract-lineage"><header><p className="eyebrow">Evidence lineage</p><h2>Every material output resolves to source evidence.</h2></header>{intelligence.evidence.map(item=><article id={item.evidence_id} key={item.evidence_id}><span>{item.entity_scope} · {item.source_family.replaceAll("_"," ")}</span><h3>{item.title}</h3><blockquote>{item.evidence_span}</blockquote>{item.source_url?<a href={item.source_url} target="_blank" rel="noreferrer">Open source ↗</a>:<span>Source URL unavailable</span>}<small>{item.publication_date} · SHA-256 {item.source_hash}</small></article>)}</section>
  </main>;
}
