"use client";

import { useEffect, useRef, useState } from "react";
import type { CompanyOperationalMap, EvidenceClass, PressureLevel, XRayHandoff, XRayLayer, XRayNode } from "@/types/operational-xray";

const layerNames:Record<XRayLayer,string>={pressure:"Pressure",volume:"Volume",financial:"Financial",technology:"Technology",customer:"Customer voice",data:"Data",ownership:"Ownership",culture:"Culture"};
const pressureLabel:Record<PressureLevel,string>={healthy:"Stable",watch:"Watch",pressured:"Pressured",critical:"Critical",unknown:"Insufficient evidence"};
const statusMark:Record<EvidenceClass,string>={Observed:"■","Strong inference":"◆",Hypothesis:"○"};

function Classification({value,compact=false}:{value:EvidenceClass;compact?:boolean}){return <span className="xray-class" title={value} data-class={value.toLowerCase().replaceAll(" ","-")}>{statusMark[value]}{compact?null:` ${value}`}</span>}
function PressureIndicator({level}:{level:PressureLevel}){return <span className="pressure-indicator" data-pressure={level}><i aria-hidden/>{pressureLabel[level]}</span>}
function nodeClassification(node:XRayNode):EvidenceClass{return node.signals.some(s=>s.classification==="Observed")?"Observed":node.signals.some(s=>s.classification==="Strong inference")?"Strong inference":"Hypothesis"}

function StageIcon({id}:{id:string}){
 const common={fill:"none",stroke:"currentColor",strokeWidth:1.7,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};
 const paths:Record<string,React.ReactNode>={
  demand:<><path {...common} d="M5 12h3l7-4v8l-7-4H5z"/><path {...common} d="M8 12v5M18 8l2-2M18 16l2 2"/></>,
  order:<><path {...common} d="M5 7h2l2 9h8l2-6H8"/><circle {...common} cx="11" cy="19" r="1"/><circle {...common} cx="17" cy="19" r="1"/></>,
  plan:<><rect {...common} x="5" y="6" width="14" height="13" rx="1"/><path {...common} d="M8 4v4M16 4v4M5 10h14M9 14h2M14 14h2"/></>,
  source:<><path {...common} d="M4 19h16M6 19V9l5 3V9l7 4v6M8 7h2V4H8z"/></>,
  make:<><circle {...common} cx="12" cy="12" r="3"/><path {...common} d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/></>,
  quality:<><path {...common} d="M12 3l7 3v5c0 5-3 8-7 10-4-2-7-5-7-10V6z"/><path {...common} d="M9 12l2 2 4-5"/></>,
  deliver:<><path {...common} d="M3 7h11v9H3zM14 10h4l3 3v3h-7z"/><circle {...common} cx="7" cy="18" r="2"/><circle {...common} cx="17" cy="18" r="2"/></>,
  support:<><path {...common} d="M5 13v-2a7 7 0 0114 0v2M5 13H3v5h4v-5zM19 13h2v5h-4v-5zM17 19c-1 1-2 2-5 2"/></>,
  cash:<><path {...common} d="M6 8c1-3 3-4 6-4 4 0 7 3 7 7s-3 7-7 7H6"/><path {...common} d="M10 8c-3 0-5 2-5 5s2 5 5 5M4 18l2 3 3-2"/><path {...common} d="M13 8h-1a2 2 0 000 4h1a2 2 0 010 4h-2M12 6v2M12 16v2"/></>,
  branch:<><path {...common} d="M4 20h16M6 20V8l6-4 6 4v12M9 20v-5h6v5M9 10h1M14 10h1"/></>,
  fulfil:<><path {...common} d="M4 7l8-4 8 4-8 4zM4 7v10l8 4 8-4V7M12 11v10"/></>,
  service:<><path {...common} d="M5 13v-2a7 7 0 0114 0v2M5 13H3v5h4v-5zM19 13h2v5h-4v-5zM17 19c-1 1-2 2-5 2"/></>,
 };
 return <svg className="stage-icon" viewBox="0 0 24 24" aria-hidden>{paths[id]??paths.make}</svg>;
}

function IntelligenceDrawer({node,onClose,map}:{node:XRayNode|XRayHandoff;onClose:()=>void;map:CompanyOperationalMap}){
 const closeRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{closeRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[onClose]);
 return <div className="xray-drawer-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><aside className="xray-drawer" role="dialog" aria-modal="true" aria-labelledby="xray-drawer-title">
  <button ref={closeRef} className="xray-close" onClick={onClose} aria-label="Close intelligence detail">×</button>
  <header><div><p className="eyebrow">Operational intelligence record</p><Classification value={nodeClassification(node)}/></div><PressureIndicator level={node.pressure}/><h2 id="xray-drawer-title">{node.name}</h2><p>{node.description}</p></header>
  <section className="drawer-analysis"><p className="eyebrow">Executive interpretation</p><blockquote>{node.interpretation}</blockquote><dl><div><dt>Trend</dt><dd>{node.trend}</dd></div><div><dt>Materiality</dt><dd>{node.materiality}</dd></div><div><dt>Evidence confidence</dt><dd>{node.confidence}</dd></div></dl></section>
  <section><p className="eyebrow">Why PIOTW thinks this</p><div className="drawer-signals">{node.signals.map(signal=>{const source=map.sourceEvidence.find(item=>item.id===signal.sourceEvidenceId);return <article key={signal.id}><header><Classification value={signal.classification}/><span>{signal.confidence} confidence</span></header><h3>{signal.title}</h3><p>{signal.detail}</p>{(signal.entityScope||signal.canonicalObjectId)&&<dl className="signal-scope"><div><dt>Applies to</dt><dd>{signal.entityScope??"Scope unavailable"}</dd></div><div><dt>PIOTW object</dt><dd>{signal.canonicalObjectId??"Not assigned"}</dd></div></dl>}<footer><span>{signal.date??"Date unavailable"}</span><span>{signal.source??"Source unavailable"}</span></footer>{signal.unknowns&&signal.unknowns.length>0&&<details><summary>What remains unknown</summary><ul>{signal.unknowns.map(item=><li key={item}>{item}</li>)}</ul></details>}{source&&<details><summary>Inspect source observation</summary><blockquote>{source.observation}</blockquote><p>Page {source.page??"not supplied"} · {source.evidenceType??source.category}</p>{signal.sourceUrl&&<a href={signal.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a>}</details>}</article>})}</div></section>
  {node.customerSignals.length>0&&<section><p className="eyebrow">Customer signals</p>{node.customerSignals.map(item=><article className="drawer-context" key={item.theme}><Classification value={item.status}/><h3>{item.theme}</h3><p>{item.signal}</p><small>{item.confidence} confidence</small></article>)}</section>}
  {node.technologies.length>0&&<section><p className="eyebrow">Technology context</p>{node.technologies.map(item=><article className="drawer-context" key={item.name}><h3>{item.name}</h3><p>{item.role}</p><small>{item.status} · {item.integration} integration complexity</small></article>)}</section>}
  {node.financials.length>0&&<section><p className="eyebrow">Potential financial consequence</p>{node.financials.map(item=><article className="drawer-financial" key={item.label}><header><span>{item.classification}</span><strong>{item.range}</strong></header><h3>{item.label}</h3><p>{item.mechanism}</p><details><summary>How estimated</summary><p>{item.estimateBasis}</p><small>Illustrative, non-additive development range. Not an audited conclusion.</small></details></article>)}</section>}
  {node.ownershipRoles.length>0&&<section><p className="eyebrow">Likely functional ownership</p><p className="drawer-owners">{node.ownershipRoles.join(" · ")}</p>{"accountability" in node&&<small>{node.accountability}</small>}</section>}
  <section className="drawer-intervention"><p className="eyebrow">Potential intervention</p><h3>{node.intervention.title}</h3><p>{node.intervention.mechanism}</p><ul>{node.intervention.actions.map(action=><li key={action}>{action}</li>)}</ul></section>
  <section><p className="eyebrow">Diligence questions</p><ol className="diligence-list">{node.diligenceQuestions.map(question=><li key={question}>{question}</li>)}</ol></section>
 </aside></div>
}

export function OperationalXRay({map}:{map:CompanyOperationalMap}){
 const optionalRows:XRayLayer[]=["volume","financial","technology","data","customer","culture"];
 const [visibleRows,setVisibleRows]=useState<Set<XRayLayer>>(()=>new Set());const [focusedRow,setFocusedRow]=useState<XRayLayer|null>(null);const [selected,setSelected]=useState<XRayNode|XRayHandoff|null>(null);const [causal,setCausal]=useState(true);const [ecommerce,setEcommerce]=useState(false);const [focusIds,setFocusIds]=useState<string[]>([]);
 const focus=(targetId:string,relatedIds:string[]=[])=>{setFocusIds(relatedIds.length?relatedIds:[targetId]);document.getElementById(`xray-${targetId}`)?.scrollIntoView({behavior:"smooth",block:"center",inline:"center"})};
 const dimmed=(id:string)=>focusIds.length>0&&!focusIds.includes(id);
 const toggleRow=(row:XRayLayer)=>setVisibleRows(current=>{const next=new Set(current);if(next.has(row)){next.delete(row);if(focusedRow===row)setFocusedRow(null)}else next.add(row);return next});
 const rowMuted=(row:XRayLayer)=>focusedRow!==null&&focusedRow!==row;
 const stageDimmed=(node:XRayNode)=>focusIds.length>0&&!focusIds.includes(node.id)&&!map.handoffs.some(h=>focusIds.includes(h.id)&&(h.from===node.name||h.to===node.name));
 const rowCell=(row:XRayLayer,node:XRayNode)=>{
  if(row==="volume")return <button className="wall-volume" data-band={node.volume?.band??"low"} onClick={()=>setSelected(node)}><i/><strong>{node.volume?.value??"Unknown"}</strong><span>{node.volume?.label??"No connected measure"}</span><small>{node.volume?.basis??"Insufficient evidence"}</small></button>;
  if(row==="financial")return <button className="wall-financial" data-materiality={node.materiality.toLowerCase()} onClick={()=>setSelected(node)}><span>£</span><strong>{node.financials[0]?.range??"Not modelled"}</strong><small>{node.financials[0]?.label??"No value pool"}</small></button>;
  if(row==="technology")return <button className="wall-technology" onClick={()=>setSelected(node)}>{node.technologies.slice(0,2).map(item=><span key={item.name} data-risk={item.integration.toLowerCase()}><strong>{item.name}</strong><small>{item.status} · {item.integration} integration</small></span>)}{node.technologies.length===0&&<span><strong>Unknown</strong><small>No connected system source</small></span>}</button>;
  if(row==="data")return <button className="wall-data" data-maturity={node.dataMaturity?.score??0} onClick={()=>setSelected(node)}><span><i style={{width:`${node.dataMaturity?.score??12}%`}}/></span><strong>{node.dataMaturity?.label??"Unknown"}</strong><small>{node.dataMaturity?.dimensions.join(" · ")??"No connected reporting source"}</small><em>{node.dataMaturity?.status??"Insufficient evidence"}</em></button>;
  if(row==="customer")return <button className="wall-customer" onClick={()=>setSelected(node)}>{node.customerSignals.slice(0,2).map(item=><span key={item.theme}><strong>{item.theme}</strong><small>{item.confidence} confidence</small></span>)}{node.customerSignals.length===0&&<span className="empty"><strong>No theme</strong><small>Insufficient evidence</small></span>}</button>;
  return <button className="wall-culture" onClick={()=>setSelected(node)}>{node.cultureSignals[0]?<><span>{node.cultureSignals[0].status}</span><strong>{node.cultureSignals[0].signal}</strong><small>Hypothesis · not a diagnosis</small></>:<><strong>No supportable signal</strong><small>Insufficient evidence</small></>}</button>;
 };
 return <main className="xray-shell wall-builder" data-mode={map.dataMode??"DEVELOPMENT_FIXTURE"}>
  <section className="xray-brief"><div className="xray-brief-title"><p className="eyebrow">PIOTW Operational X-Ray · {map.company.period}</p><h1>{map.company.name}</h1><span>{map.company.archetype} · <b>{map.dataMode==="REAL_COMPANY"?"Real public evidence":"Development demonstration"}</b></span></div><div className="xray-brief-thesis"><p>{map.summary.thesis}</p><small>{map.summary.methodologyStatus}</small>{map.entityScope&&<p className="scope-note"><b>Primary Wall scope:</b> {map.entityScope.primary}. {map.entityScope.note}</p>}</div><dl><div><dt>{map.dataMode==="REAL_COMPANY"?"Operational rating":"Position"}</dt><dd>{map.summary.rating}</dd></div><div><dt>Primary investigation</dt><dd>{map.summary.primaryConstraint}</dd></div><div><dt>Financial view</dt><dd>{map.summary.valueTrapped}{map.dataMode!=="REAL_COMPANY"&&<small>illustrative</small>}</dd></div><div><dt>Evidence confidence</dt><dd>{map.summary.confidence}</dd></div></dl></section>
  <section className="wall-section" aria-labelledby="wall-title">
   <header className="wall-header"><div><p className="eyebrow">The Wall · whole-company operating map</p><h2 id="wall-title">See the pressure. Follow the consequence.</h2></div><div className="heat-legend" aria-label="Operational pressure legend"><span data-pressure="healthy"><i/>Stable</span><span data-pressure="watch"><i/>Watch</span><span data-pressure="pressured"><i/>Pressured</span><span data-pressure="critical"><i/>Critical</span><span data-pressure="unknown"><i/>Insufficient evidence</span></div></header>
   <div className="wall-command"><fieldset className="layer-controls wall-build-controls"><legend>Build the Wall</legend><span className="always-on">✓ Value stream</span>{optionalRows.map(key=><button type="button" key={key} aria-pressed={visibleRows.has(key)} onClick={()=>toggleRow(key)}><i aria-hidden/>{visibleRows.has(key)?"−":"+"} {layerNames[key]}</button>)}<button className="show-full-wall" onClick={()=>{setVisibleRows(new Set(optionalRows));setFocusedRow(null)}}>Show full Wall</button></fieldset><div className="hotspot-rail"><span>Cross-section</span>{map.hotspots.map(item=><button key={item.id} aria-label={`Focus ${item.title}`} onClick={()=>focus(item.targetId,item.relatedIds)}><b>0{item.rank}</b><strong>{item.title}</strong><small>{item.value}</small></button>)}{focusIds.length>0&&<button className="clear-focus" onClick={()=>setFocusIds([])}>Clear focus</button>}</div></div>
   {map.coverageRows&&<details className="wall-coverage"><summary><span>Coverage & source gaps</span><small>{map.coverageRows.filter(item=>item.state==="LIVE / SOURCE-BACKED").length} fully source-backed rows · inspect what PIOTW does not know</small></summary><div>{map.coverageRows.map(item=><article key={item.row} data-state={item.state}><header><strong>{layerNames[item.row as XRayLayer]??"Value stream"}</strong><span>{item.state}</span></header><p>{item.note}</p><small><b>Contributing:</b> {item.sourceFamilies.join(" · ")||"None"}</small><small><b>Missing:</b> {item.missingSource}</small></article>)}</div></details>}
   <div className="layered-wall" aria-label="Additive operational intelligence wall"><aside className="wall-row-rail"><div className="wall-rail-zone">Operating layer</div><div className="wall-rail-label ownership-label"><span>Ownership</span><small>Typical accountability</small></div><div className="wall-rail-label value-label"><span>Value stream</span><small>Always visible</small></div>{optionalRows.filter(row=>visibleRows.has(row)).map(row=><div className={`wall-rail-label ${row}-label`} key={row} data-muted={rowMuted(row)}><button onClick={()=>setFocusedRow(focusedRow===row?null:row)}><span>{layerNames[row]}</span><small>{focusedRow===row?"Show full Wall":"Focus row"}</small></button><button className="row-collapse" aria-label={`Collapse ${layerNames[row]}`} onClick={()=>toggleRow(row)}>−</button></div>)}</aside><div className="layered-wall-scroll"><div className="layered-wall-canvas"><div className="wall-zones" aria-hidden><span className="zone-commercial">Commercial</span><span className="zone-core">Core operations</span><span className="zone-customer">Customer</span><span className="zone-cash">Cash</span></div><div className="wall-row ownership-row">{map.stages.map(node=><button key={node.id} data-dimmed={stageDimmed(node)} onClick={()=>setSelected(node)}><span>Likely functional owner</span><strong>{node.ownershipRoles[0]??"Unknown"}</strong><i>↓</i></button>)}</div><div className="wall-row value-stream-row">
    {map.stages.map((node,index)=><div className="flow-segment" key={node.id} data-dimmed={stageDimmed(node)}><div className="node-column"><button id={`xray-${node.id}`} className="heat-node" data-pressure={node.pressure} data-materiality={node.materiality.toLowerCase()} data-confidence={node.confidence.toLowerCase()} data-focused={focusIds.includes(node.id)} onClick={()=>setSelected(node)} aria-label={`${node.name}: ${pressureLabel[node.pressure]} pressure, ${node.materiality} materiality, ${node.confidence} evidence confidence`}><span className="node-ring" aria-hidden/><span className="node-core"><StageIcon id={node.id}/><small>{String(index+1).padStart(2,"0")}</small></span><span className="confidence-mark" title={`${node.confidence} evidence confidence`}><b>{node.confidence.slice(0,1)}</b></span></button><h3>{node.name}</h3><div className="node-status"><PressureIndicator level={node.pressure}/><Classification value={nodeClassification(node)} compact/></div></div>{index<map.handoffs.length&&(()=>{const handoff=map.handoffs[index];return <button id={`xray-${handoff.id}`} className="heat-handoff" data-pressure={handoff.pressure} data-volume={handoff.volume?.band??"medium"} data-dimmed={dimmed(handoff.id)} data-focused={focusIds.includes(handoff.id)} onClick={()=>setSelected(handoff)} aria-label={`${handoff.name} handoff: ${pressureLabel[handoff.pressure]} pressure; ${handoff.volume?.value??"unknown"} volume`}><span className="flow-line"/><i className="flow-arrow"/><b>{pressureLabel[handoff.pressure]}</b></button>})()}</div>)}
   </div>{optionalRows.filter(row=>visibleRows.has(row)).map(row=><div className={`wall-row intelligence-row ${row}-row`} data-muted={rowMuted(row)} key={row}>{map.stages.map(node=><div key={node.id} className="wall-intelligence-cell" data-dimmed={stageDimmed(node)}>{rowCell(row,node)}</div>)}</div>)}</div></div></div>
   <div className="map-footer-tools"><button className="propagation-toggle" aria-expanded={causal} onClick={()=>setCausal(value=>!value)}>Propagation path <b>{causal?"Shown":"Hidden"}</b></button>{causal&&<div className="propagation-path"><Classification value={map.causalChains[0].classification}/>{map.causalChains[0].nodes.map((item,index)=><span key={item}>{item}{index<map.causalChains[0].nodes.length-1&&<i>→</i>}</span>)}<small>Apparent path, not proven causation</small></div>}</div>
   <div className="ecommerce-flow"><button aria-expanded={ecommerce} onClick={()=>setEcommerce(value=>!value)}><span>Digital branch</span><strong>Ecommerce order-to-service sub-flow</strong><i>{ecommerce?"−":"+"}</i></button>{ecommerce&&<div>{["Discover","Configure","Checkout","Promise","Track","Resolve"].map((item,index)=><article key={item}><span>0{index+1}</span><strong>{item}</strong><small>{index===3||index===4?"Watch":"Demo"}</small></article>)}</div>}</div>
  </section>{selected&&<IntelligenceDrawer node={selected} map={map} onClose={()=>setSelected(null)}/>}
 </main>
}
