import Link from "next/link";
import { notFound } from "next/navigation";
import { IntelligenceNav } from "@/components/intelligence-nav";
import { PeriodSelector } from "@/components/period-selector";
import { filterChangesByPeriod, profileChanges, selectedPeriod, sincePreviousChanges } from "@/lib/data/intelligence-changes";
import { getCompanyIntelligenceSnapshot } from "@/lib/data/company-intelligence";

const dateOnly = (value: string) => new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(new Date(value));
const dateTime = (value: string) => new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/London"}).format(new Date(value));
export default async function CompanyEvidenceBrief({ params, searchParams }: { params: Promise<{ companyId: string }>; searchParams: Promise<{ period?: string }> }) {
  const { companyId } = await params; const profile = await getCompanyIntelligenceSnapshot(companyId); if(!profile) notFound();
  const query=await searchParams; const period=selectedPeriod(query.period); const complete=profileChanges(profile); const changes=period==="previous"?sincePreviousChanges(profile):filterChangesByPeriod(complete,period);
  const current=profile.careers_history?.at(-1); const atomic=(profile.atomic_observations??[]).filter((item)=>item.decision==="ACCEPT");
  return <main className="print-brief"><div className="print-controls"><IntelligenceNav companyId={companyId}/><PeriodSelector period={period}/><span>Use browser Print / Save as PDF</span></div>
    <header><p>PIOTW outside-in factual intelligence — experimental prototype.</p><h1>{profile.display_name}</h1><dl><div><dt>Snapshot generated</dt><dd>{dateTime(profile.observation_date)}</dd></div><div><dt>Selected period</dt><dd>{period==="previous"?"Since previous observation":period==="all"?"All available history":`Latest ${period} days of recorded evidence`}</dd></div><div><dt>Factual changes</dt><dd>{changes.length}</dd></div><div><dt>Prediction</dt><dd>NOT YET VALIDATED</dd></div></dl></header>
    <section><h2>What changed</h2><p className="brief-explanation">Appears because {changes.length} factual changes were recorded in the selected period. No materiality or risk is inferred.</p>{changes.length?<ol className="numbered-facts">{changes.map((item,index)=><li key={item.id}><span>[E{index+1}]</span><div><time>{dateOnly(item.date)}</time><p>{item.statement}</p></div></li>)}</ol>:<p>INSUFFICIENT OBSERVED DATA for this period.</p>}</section>
    <section><h2>Latest observations</h2>{atomic.length?<ul className="brief-observations">{atomic.slice(0,5).map((item)=><li key={item.observation_id}>{item.subject} {item.action_or_state} {item.object}.</li>)}</ul>:<p>No accepted issuer-document observation is available for this company.</p>}</section>
    <section><h2>Careers facts</h2>{current?<dl className="brief-metrics"><div><dt>Open</dt><dd>{current.open_roles}</dd></div><div><dt>New</dt><dd>{current.new_roles}</dd></div><div><dt>Persistent</dt><dd>{current.persistent_roles}</dd></div><div><dt>Absent once</dt><dd>{current.absent_once_roles}</dd></div><div><dt>Confirmed closed</dt><dd>{current.confirmed_closed_roles}</dd></div><div><dt>Reopened</dt><dd>{current.reopened_roles}</dd></div></dl>:<p>Careers evidence unavailable.</p>}</section>
    <section><h2>Source coverage</h2><ul>{profile.source_freshness.map((source)=><li key={String(source.source_family)}><strong>{String(source.source_family).replaceAll("_"," ")}</strong>: {String(source.health)}; last success {source.last_successful_fetch?dateTime(String(source.last_successful_fetch)):"not available"}.</li>)}<li><strong>Issuer observation layer</strong>: {atomic.length?`${atomic.length} development observations`:`unavailable`}.</li><li><strong>Resolved procurement</strong>: unavailable.</li></ul></section>
    <section><h2>What we do not know yet</h2><ul><li>Whether any observed change is important, positive, negative or predictive.</li><li>Peer-relative position or benchmark.</li><li>Company-level procurement activity without approved entity resolution.</li><li>Evidence for {profile.dimensions.filter((item)=>item.coverage_status!=="OBSERVED").length} of eight operational dimensions.</li></ul></section>
    <section className="evidence-references"><h2>Evidence references</h2>{changes.map((item,index)=><article key={item.id}><header><strong>[E{index+1}] {item.source_family.replaceAll("_"," ")}</strong><time>{dateOnly(item.date)}</time></header>{item.evidence_span?<blockquote>{item.evidence_span}</blockquote>:<p>Lifecycle fact retained in the immutable careers collection record.</p>}{item.source_url?<a href={item.source_url}>Original source ↗</a>:<span>Original source URL is not exposed by this collector record.</span>}<dl><div><dt>Source status</dt><dd>{item.source_family==="careers_ats"?(profile.source_freshness.find((source)=>String(source.source_family)==="careers_ats")?.health as string??"unknown"):"source retained"}</dd></div><div><dt>Source hash</dt><dd>{item.source_hash??"not available"}</dd></div><div><dt>Observation ID</dt><dd>{item.observation_id??"not applicable"}</dd></div><div><dt>Version</dt><dd>{item.version}</dd></div></dl></article>)}</section>
    <footer><p>Experimental factual prototype. No score, rating, benchmark or prediction.</p><Link href={`/intelligence/${companyId}`}>Return to interactive company page</Link></footer>
  </main>;
}
