PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS ee01_companies(company_id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ee01_sources(source_id TEXT PRIMARY KEY, source_type TEXT NOT NULL, title TEXT NOT NULL, url TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ee01_collector_runs(run_id TEXT PRIMARY KEY, collector_version TEXT NOT NULL, started_at TEXT NOT NULL, finished_at TEXT, status TEXT NOT NULL, cost_usd REAL NOT NULL DEFAULT 0, duration_seconds REAL);
CREATE TABLE IF NOT EXISTS ee01_raw_evidence(evidence_id TEXT PRIMARY KEY, company_id TEXT NOT NULL, source_id TEXT NOT NULL, reporting_period TEXT NOT NULL, publication_date TEXT NOT NULL, observation_date TEXT, collected_at TEXT NOT NULL, information_available_at TEXT NOT NULL, content_hash TEXT NOT NULL, raw_storage_path TEXT NOT NULL, collector_version TEXT NOT NULL, FOREIGN KEY(company_id) REFERENCES ee01_companies(company_id), FOREIGN KEY(source_id) REFERENCES ee01_sources(source_id));
CREATE TABLE IF NOT EXISTS ee01_extraction_runs(run_id TEXT PRIMARY KEY, parser_version TEXT NOT NULL, started_at TEXT NOT NULL, finished_at TEXT, llm_model TEXT, prompt_version TEXT, cost_usd REAL NOT NULL DEFAULT 0, duration_seconds REAL);
CREATE TABLE IF NOT EXISTS ee01_observations(observation_id TEXT PRIMARY KEY, company_id TEXT NOT NULL, observation_type TEXT NOT NULL, reporting_period TEXT NOT NULL, value_json TEXT, unit TEXT, currency TEXT, source_evidence_id TEXT NOT NULL, evidence_span TEXT NOT NULL, page_or_section TEXT NOT NULL, publication_date TEXT NOT NULL, observation_date TEXT, information_available_at TEXT NOT NULL, extraction_confidence REAL NOT NULL, parser_version TEXT NOT NULL, extraction_method TEXT NOT NULL, llm_model TEXT, prompt_version TEXT, extracted_at TEXT NOT NULL, validation_status TEXT NOT NULL, quantified INTEGER NOT NULL, metadata_json TEXT NOT NULL, FOREIGN KEY(source_evidence_id) REFERENCES ee01_raw_evidence(evidence_id));
CREATE TABLE IF NOT EXISTS ee01_review_decisions(decision_id TEXT PRIMARY KEY, observation_id TEXT NOT NULL, decision TEXT NOT NULL, reviewer TEXT NOT NULL, decided_at TEXT NOT NULL, corrected_value_json TEXT, corrected_unit TEXT, note TEXT NOT NULL, FOREIGN KEY(observation_id) REFERENCES ee01_observations(observation_id));
CREATE TABLE IF NOT EXISTS ee01_events(event_id TEXT PRIMARY KEY, company_id TEXT NOT NULL, event_type TEXT NOT NULL, taxonomy_group TEXT NOT NULL, reporting_period TEXT NOT NULL, event_date TEXT NOT NULL, information_available_at TEXT NOT NULL, evidence_span TEXT NOT NULL, quantified INTEGER NOT NULL, severity REAL, novelty TEXT NOT NULL, extraction_confidence REAL NOT NULL, taxonomy_version TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ee01_event_evidence(event_id TEXT NOT NULL, observation_id TEXT NOT NULL, evidence_id TEXT NOT NULL, PRIMARY KEY(event_id,observation_id), FOREIGN KEY(event_id) REFERENCES ee01_events(event_id), FOREIGN KEY(observation_id) REFERENCES ee01_observations(observation_id), FOREIGN KEY(evidence_id) REFERENCES ee01_raw_evidence(evidence_id));
CREATE TABLE IF NOT EXISTS ee01_feature_definitions(feature_id TEXT NOT NULL, version TEXT NOT NULL, definition_json TEXT NOT NULL, effective_from TEXT NOT NULL, PRIMARY KEY(feature_id,version));
CREATE TABLE IF NOT EXISTS ee01_feature_snapshots(snapshot_id TEXT PRIMARY KEY, company_id TEXT NOT NULL, feature_id TEXT NOT NULL, feature_version TEXT NOT NULL, as_of_date TEXT NOT NULL, value_json TEXT, unit TEXT NOT NULL, calculation TEXT NOT NULL, quality REAL NOT NULL, created_at TEXT NOT NULL, UNIQUE(company_id,feature_id,feature_version,as_of_date));
CREATE TABLE IF NOT EXISTS ee01_feature_provenance(snapshot_id TEXT NOT NULL, observation_id TEXT, event_id TEXT, evidence_id TEXT, FOREIGN KEY(snapshot_id) REFERENCES ee01_feature_snapshots(snapshot_id), FOREIGN KEY(observation_id) REFERENCES ee01_observations(observation_id), FOREIGN KEY(event_id) REFERENCES ee01_events(event_id), FOREIGN KEY(evidence_id) REFERENCES ee01_raw_evidence(evidence_id));
CREATE TABLE IF NOT EXISTS ee01_jobs(identity TEXT PRIMARY KEY, company_id TEXT NOT NULL, posting_id TEXT NOT NULL, title TEXT NOT NULL, function TEXT, seniority TEXT, location TEXT, source_url TEXT NOT NULL, collected_at TEXT NOT NULL, first_seen TEXT NOT NULL, last_seen TEXT NOT NULL, status TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ee01_evidence_cutoff_idx ON ee01_raw_evidence(company_id, information_available_at);
CREATE INDEX IF NOT EXISTS ee01_observation_cutoff_idx ON ee01_observations(company_id, information_available_at);

