import Link from "next/link";
import { NorthStarNav } from "@/components/north-star-nav";
import { northStarCompanies } from "@/lib/data/north-star-fixtures";

export default async function NorthStarPortfolio({searchParams}:{searchParams:Promise<{sort?:string;state?:string}>}){
  const query=await searchParams; const state=query.state??"All"; const sort=query.sort??"movement";
  let companies=state==="All"?northStarCompanies:northStarCompanies.filter(c=>c.state===state);
  companies=[...companies].sort(sort==="rating"?(a,b)=>b.rating-a.rating:sort==="confidence"?(a,b)=>a.confidence.localeCompare(b.confidence):(a,b)=>Math.abs(b.rating-b.priorRating)-Math.abs(a.rating-a.priorRating));
  const states=["All",...new Set(northStarCompanies.map(c=>c.state))];
  return <div className="northstar-shell"><NorthStarNav/><header className="northstar-hero"><div><p className="eyebrow">Future product experience · illustrative</p><h1>The operating picture,<br/><em>before it hits the numbers.</em></h1></div><p>A synthetic portfolio showing how PIOTW could turn traceable evidence into comparable operating intelligence, forward scenarios and precise diligence questions.</p></header><section className="northstar-portfolio"><header><div><p className="eyebrow">Portfolio intelligence</p><h2>Eight companies. One operating language.</h2></div><form><label>State<select name="state" defaultValue={state}>{states.map(s=><option key={s}>{s}</option>)}</select></label><label>Sort by<select name="sort" defaultValue={sort}><option value="movement">Largest movement</option><option value="rating">Rating</option><option value="confidence">Confidence</option></select></label><button>Apply</button></form></header><div className="portfolio-table"><div className="portfolio-row portfolio-head"><span>Company</span><span>Illustrative rating</span><span>Movement</span><span>Strongest / weakest dimension</span><span>Forward event</span><span>Confidence</span></div>{companies.map(c=>{const sorted=[...c.dimensions].sort((a,b)=>b.score-a.score);return <Link className="portfolio-row" href={`/north-star/${c.id}`} key={c.id}><span><strong>{c.name}</strong><small>{c.sector} · {c.state}</small></span><span className="rating-cell"><b>{c.rating}</b><small>/100 concept</small></span><span className={c.rating>=c.priorRating?"up":"down"}>{c.rating>=c.priorRating?"↑":"↓"} {Math.abs(c.rating-c.priorRating)} pts</span><span><small>Strength</small>{sorted[0].name}<small>Watch</small>{sorted.at(-1)?.name}</span><span>{c.events[0].name}<small>{Math.round(c.events[0].sixMonth)}% · 6 months</small></span><span><b>{c.confidence}</b><small>{c.coverage}</small></span></Link>})}</div></section><section className="northstar-boundary"><strong>What this is</strong><p>A deliberately rich product prototype built from fictional fixtures. It demonstrates the decisions PIOTW could support.</p><strong>What this is not</strong><p>A validated score, prediction engine, or claim about a real company.</p></section></div>
}
