import Link from "next/link";
import {FounderRetrospectivePanel} from "@/components/founder-retrospective-panel";
import {LabModeNav} from "@/components/lab-mode-nav";
import {benchmarkFeatures,diligenceQuestions,estateSources,falsifiers,peerCohort,peerMedian,tpEstateHistory,tpPeerGap,valueScenarios} from "@/lib/data/real-company-lab/estate-productivity";

export default function EstateProductivityLab(){return <div className="lab-shell value-engine"><LabModeNav/><div className="ve-runtime-link"><Link href="/intelligence/travis-perkins/value">Open canonical v0.1 intelligence object →</Link></div>
<header className="ve-hero"><div><Link href="/lab">← Real Company Lab</Link><p className="eyebrow">PIOTW VALUE ENGINE v0.1 · ESTATE PRODUCTIVITY</p><h1>A sharp estate reset has not yet produced visible branch-productivity recovery.</h1><p>Travis Perkins Merchanting contracted its footprint by 5.9% in 2024, then expanded only 0.4% in 2025 versus a 2.5% peer median. Revenue per branch continued to edge down.</p></div><aside><span>DEVELOPMENT BENCHMARK</span><strong>−2.12ppt</strong><p>2025 net estate change versus eligible peer median</p><b>NOT YET VALIDATED</b></aside></header>

<section className="ve-first"><article><p className="eyebrow">The three conclusions</p><ol><li><b>Reset:</b> 51 closures and 6 openings reduced Merchanting branches from 769 to 724 in 2024.</li><li><b>Stabilisation:</b> 2025 returned to +3 net branches, but growth remained below the eligible peer median.</li><li><b>Unresolved productivity:</b> the coarse revenue/location proxy fell from £5.50m to £5.12m between 2022 and 2025.</li></ol></article><article><p className="eyebrow">Top intervention opportunity</p><h2>Branch-level estate triage and format productivity</h2><p>Separate genuinely underproductive sites from cyclically impaired but strategically valuable locations; prioritise relocation, consolidation or capital recycling only where service density survives.</p><small>OPPORTUNITY SUPPORTED · EBITDA VALUE NOT YET SUPPORTABLE</small></article><article><p className="eyebrow">Illustrative cash range</p><div>{valueScenarios.map(s=><span key={s.label}><small>{s.label}</small><strong>{s.value}</strong></span>)}</div><p>Annual gross property cash-proceeds continuation scenario—not incremental EBITDA or a forecast.</p></article></section>

<section className="ve-benchmark"><header><p className="eyebrow">Where Travis Perkins differs</p><h2>One defensible peer feature. Three withheld.</h2></header><div>{benchmarkFeatures.map(f=><article key={f.name}><span>{f.name}</span><strong>{f.tp}</strong><b>{f.position}</b><p>{f.meaning}</p><small>PEER: {f.peer}</small></article>)}</div><p className="ve-method">Eligible 2025 cohort: Travis Perkins Merchanting, Grafton Great Britain, Howdens UK and Lords Merchanting. SIG UK is retained as a contextual peer but excluded because a comparable opening/closing bridge is unavailable.</p></section>

<section className="ve-peer"><header><p className="eyebrow">Matched peer cohort · 2025</p><h2>Comparison before conclusion.</h2><p>DEVELOPMENT BENCHMARK — NOT YET VALIDATED</p></header><div>{peerCohort.map(p=><article key={p.company} className={p.company.startsWith("Travis")?"target":""}><h3>{p.company}</h3><p>{p.model}</p><strong>{p.netRate===null?"WITHHELD":`${p.netRate>0?"+":""}${p.netRate}%`}</strong><small>{p.eligible?`${p.start} → ${p.end}`:"INSUFFICIENT MOVEMENT DATA"}</small><a href={`#${p.sourceId}`}>Evidence</a></article>)}</div><footer><span>Peer median <b>+{peerMedian}%</b></span><span>TP gap <b>{tpPeerGap}ppt</b></span><span>TP development percentile <b>33rd of 4</b></span></footer></section>

<section className="ve-history"><header><p className="eyebrow">Point-in-time estate reconstruction</p><h2>The contraction was episodic; the productivity question persists.</h2></header><div>{tpEstateHistory.map(y=><article key={y.year}><time>{y.year}</time><strong>{y.branches}</strong><span>branches</span><dl><div><dt>Net change</dt><dd>{y.net===null?"Unavailable":`${y.net>0?"+":""}${y.net}`}</dd></div><div><dt>Revenue</dt><dd>£{y.revenue}m</dd></div><div><dt>Revenue/branch</dt><dd>£{y.revenuePerBranch.toFixed(2)}m</dd></div></dl><small>{y.coverage}</small></article>)}</div></section>

<section className="ve-synthesis"><header><p className="eyebrow">What one source cannot tell you</p><h2>No single source states this conclusion.</h2></header><p>PIOTW combines annual branch bridges, external peer networks, estate/planning cases, branch-format evidence, impairment review scope and property cash proceeds. Together they indicate a network that underwent a concentrated reset, then stabilised without an observable productivity rebound—creating a diligence case for selective triage, not an assumption of blanket closure.</p><div>{["2024 opening/closure bridge","2025 peer footprint movement","2022–25 revenue/location proxy","209-branch impairment population","£51m–£62m property proceeds","relocation and planning evidence"].map(x=><span key={x}>{x}</span>)}</div></section>

<section className="ve-opportunity"><header><p className="eyebrow">Decision-grade intervention hypothesis</p><h2>Triage the estate by contribution, service density and format economics.</h2></header><div><article><h3>Plausible mechanism</h3><p>Demand weakness, local overlap, legacy formats and uneven investment may leave a mixed population: some sites suitable for consolidation or relocation, others strategically important despite accounting impairment. Public evidence cannot distinguish them branch by branch.</p></article><article><h3>Ask management</h3><ol>{diligenceQuestions.map(q=><li key={q}>{q}</li>)}</ol></article><article><h3>What would falsify it</h3><ul>{falsifiers.map(f=><li key={f}>{f}</li>)}</ul></article></div></section>

<section className="ve-value"><header><p className="eyebrow">Transparent value bridge</p><h2>Capital opportunity measured; EBITDA withheld.</h2></header><div className="value-flow"><span>PUBLIC FACT<small>£62m and £51m property cash proceeds</small></span><i>→</i><span>DERIVED INPUT<small>£56.5m two-year average</small></span><i>→</i><span>ASSUMPTION<small>50% / 75% / 100% recurrence</small></span><i>→</i><span>SCENARIO OUTPUT<small>£28m / £42m / £57m gross cash proceeds</small></span></div><p>This is a continuation capacity scenario, not incremental value, profit or guidance. EBITDA is withheld because public data does not expose comparable branch contribution, occupancy cost or post-transfer customer retention. Claiming it would manufacture precision.</p></section>

<section className="ve-evidence"><header><p className="eyebrow">Evidence lineage</p><h2>Every benchmark number has a source.</h2></header>{estateSources.map(s=><article id={s.id} key={s.id}><span>{s.entity}</span><h3>{s.title}</h3><p>“{s.evidenceSpan}”</p><a href={s.url} target="_blank" rel="noreferrer">Open source ↗</a><small>{s.publicationDate} · SHA-256 {s.hash}</small></article>)}</section>
<FounderRetrospectivePanel entityId="tp-estate-value-engine" asOf="2026-08-19"/></div>}
